services:
  - type: web
    name: fast-convert-server
    runtime: docker
    env: docker
    dockerContext: .
    dockerfilePath: server/Dockerfile
    envVars:
      - key: PORT
        value: 5000
